apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: veeranarni/hotstar:latest #docker hub private registry
        #image: 992382358200.dkr.ecr.ap-south-1.amazonaws.com/maventomcat:latest # ecr registry reference 
        ports:
        - containerPort: 3000  # Port your application listens on
